# Generated by Django 5.2.6 on 2025-10-06 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='purchase',
            options={'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
    ]
