# Generated by Django 5.2.5 on 2025-11-07 18:04

import django.core.validators
import maintenance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_alter_maintenance_cost_alter_maintenance_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenance',
            options={'ordering': ['-date'], 'verbose_name': 'Mantenimiento', 'verbose_name_plural': 'Mantenimientos'},
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Costo'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Descripción'),
        ),
    ]
