# Generated by Django 5.2.6 on 2025-10-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_category_alter_brand_options_alter_carmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos_app/'),
        ),
    ]
