# Generated by Django 5.2.5 on 2025-11-07 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_alter_carmodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.brand', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.category', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='combustible',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='autos_app/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='motor',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Potencia'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmision',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterModelTable(
            name='brand',
            table='marcas',
        ),
        migrations.AlterModelTable(
            name='carmodel',
            table='modelos_autos',
        ),
        migrations.AlterModelTable(
            name='category',
            table='categorias',
        ),
    ]
