# Generated by Django 5.2.5 on 2025-11-07 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_alter_brand_name_alter_carmodel_brand_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE auth_group RENAME TO grupos;",
            reverse_sql="ALTER TABLE grupos RENAME TO auth_group;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_group_permissions RENAME TO permisos_grupo;",
            reverse_sql="ALTER TABLE permisos_grupo RENAME TO auth_group_permissions;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_permission RENAME TO permisos;",
            reverse_sql="ALTER TABLE permisos RENAME TO auth_permission;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user RENAME TO usuarios;",
            reverse_sql="ALTER TABLE usuarios RENAME TO auth_user;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user_groups RENAME TO grupos_usuario;",
            reverse_sql="ALTER TABLE grupos_usuario RENAME TO auth_user_groups;"
        ),
        migrations.RunSQL(
            "ALTER TABLE auth_user_user_permissions RENAME TO permisos_usuario;",
            reverse_sql="ALTER TABLE permisos_usuario RENAME TO auth_user_user_permissions;"
        ),
        migrations.RunSQL(
            "ALTER TABLE django_admin_log RENAME TO registro_admin;",
            reverse_sql="ALTER TABLE registro_admin RENAME TO django_admin_log;"
        ),
        migrations.RunSQL(
            "ALTER TABLE django_content_type RENAME TO tipos_contenido;",
            reverse_sql="ALTER TABLE tipos_contenido RENAME TO django_content_type;"
        ),
        migrations.RunSQL(
            "ALTER TABLE django_session RENAME TO sesiones;",
            reverse_sql="ALTER TABLE sesiones RENAME TO django_session;"
        ),
    ]
