# Generated by Django 5.2.5 on 2025-11-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_auth_tables'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE grupos RENAME TO auth_group;",
            reverse_sql="ALTER TABLE auth_group RENAME TO grupos;"
        ),
        migrations.RunSQL(
            "ALTER TABLE permisos_grupo RENAME TO auth_group_permissions;",
            reverse_sql="ALTER TABLE auth_group_permissions RENAME TO permisos_grupo;"
        ),
        migrations.RunSQL(
            "ALTER TABLE permisos RENAME TO auth_permission;",
            reverse_sql="ALTER TABLE auth_permission RENAME TO permisos;"
        ),
        migrations.RunSQL(
            "ALTER TABLE usuarios RENAME TO auth_user;",
            reverse_sql="ALTER TABLE auth_user RENAME TO usuarios;"
        ),
        migrations.RunSQL(
            "ALTER TABLE grupos_usuario RENAME TO auth_user_groups;",
            reverse_sql="ALTER TABLE auth_user_groups RENAME TO grupos_usuario;"
        ),
        migrations.RunSQL(
            "ALTER TABLE permisos_usuario RENAME TO auth_user_user_permissions;",
            reverse_sql="ALTER TABLE auth_user_user_permissions RENAME TO permisos_usuario;"
        ),
        migrations.RunSQL(
            "ALTER TABLE registro_admin RENAME TO django_admin_log;",
            reverse_sql="ALTER TABLE django_admin_log RENAME TO registro_admin;"
        ),
        migrations.RunSQL(
            "ALTER TABLE tipos_contenido RENAME TO django_content_type;",
            reverse_sql="ALTER TABLE django_content_type RENAME TO tipos_contenido;"
        ),
        migrations.RunSQL(
            "ALTER TABLE sesiones RENAME TO django_session;",
            reverse_sql="ALTER TABLE django_session RENAME TO sesiones;"
        ),
    ]
