# Generated by Django 5.2.5 on 2025-11-07 18:04

import django.core.validators
import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_revert_builtin_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='combustible',
            field=models.CharField(blank=True, choices=[('Gasolina', 'Gasolina'), ('Diésel', 'Diésel'), ('Eléctrico', 'Eléctrico'), ('Híbrido', 'Híbrido'), ('Gas Natural', 'Gas Natural')], max_length=100, null=True, verbose_name='Combustible'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='motor',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.\\,]+$', 'El motor solo puede contener letras, números, espacios, guiones, puntos y comas.')], verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='potencia',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9\\s\\-\\.]+$', 'La potencia solo puede contener letras, números, espacios, guiones y puntos.')], verbose_name='Potencia'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='transmision',
            field=models.CharField(blank=True, choices=[('Manual', 'Manual'), ('Automática', 'Automática'), ('CVT', 'CVT'), ('Dual-Clutch', 'Dual-Clutch')], max_length=100, null=True, verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2030)], verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Nombre'),
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('brand', 'name', 'year')},
        ),
    ]
